// <auto-generated />
namespace _2.Data_Layer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class applicantTableChangedToStringCandidateId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applicantTableChangedToStringCandidateId));
        
        string IMigrationMetadata.Id
        {
            get { return "202312031742250_applicantTableChangedToStringCandidateId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
