// <auto-generated />
namespace _2.Data_Layer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class applicantTableAddedStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applicantTableAddedStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202312031738398_applicantTableAddedStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
